// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig } from '@prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // We rely on the environment variable being set (e.g. by Docker or manually in shell)
    url: process.env.DATABASE_URL,
  },
});
